msm: ipa: fix -Wmisleading-indentation
Fixes:
drivers/platform/msm/ipa/ipa_clients/ipa_uc_offload.c:676:3: error:
misleading indentation; statement is not part of the previous 'if'
[-Werror,-Wmisleading-indentation]
ipa_uc_ntn_free_conn_smmu_info(&ntn_ctx->conn.ul);
^
drivers/platform/msm/ipa/ipa_clients/ipa_uc_offload.c:674:2: note:
previous statement is here
if (ntn_ctx->conn.dl.smmu_enabled)
^

Match how this was fixed in floral. See floral kernel
commit 1913ba886aa ("msm: arm64: fix compiler warnings due to improper
braces or indentation")

Bug: 155426751
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: I01ab3f8cfe598ce391d958eaf92ef510e0fb0540