Revert "sound: soc: codecs: tas2560-core: silence the unused variable"
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]

This reverts commit 526cea9b93d001bafe5ac18757b204f570a243ed.